package com.petcare.backend.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.petcare.backend.dto.admin.social.request.ModerationActionRequest;
import com.petcare.backend.dto.admin.social.request.ResolveSocialReportRequest;
import com.petcare.backend.exception.BadRequestException;
import com.petcare.backend.exception.ResourceNotFoundException;
import com.petcare.backend.model.*;
import com.petcare.backend.model.enums.*;
import com.petcare.backend.repository.*;
import com.petcare.backend.security.UserPrincipal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.Path;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.*;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = org.mockito.quality.Strictness.LENIENT)
class AdminSocialModerationServiceImplTest {
 @Mock PostRepository posts;@Mock PostCommentRepository comments;@Mock PostReactionRepository postReactions;@Mock CommentReactionRepository commentReactions;@Mock SocialReportRepository reports;@Mock ModerationActionRepository actions;@Mock UserRepository users;@Mock UserPrincipal principal;AdminSocialModerationServiceImpl service;
 @BeforeEach void init(){service=new AdminSocialModerationServiceImpl(posts,comments,postReactions,commentReactions,reports,actions,users);when(principal.getId()).thenReturn(10L);when(posts.save(any())).thenAnswer(i->i.getArgument(0));when(comments.save(any())).thenAnswer(i->i.getArgument(0));when(reports.save(any())).thenAnswer(i->i.getArgument(0));}
 User user(long id){User u=new User();u.setId(id);u.setEmail("u"+id+"@test.com");u.setFullName("User "+id);return u;} Post post(){Post p=new Post();p.setId(1L);p.setUser(user(2));p.setCaption("hello");p.setStatus(PostStatus.PUBLISHED);p.setPrivacy(PostPrivacy.PUBLIC);return p;} PostComment comment(){PostComment c=new PostComment();c.setId(2L);c.setPost(post());c.setUser(user(3));c.setCommentText("text");c.setStatus(CommentStatus.VISIBLE);return c;} SocialReport report(SocialReport.ModerationTargetType type){SocialReport r=new SocialReport();r.setId(5L);r.setTargetType(type);r.setTargetId(type==SocialReport.ModerationTargetType.post?1L:2L);r.setReporter(user(4));r.setReason(SocialReport.ReportReason.spam);r.setStatus(SocialReport.ReportStatus.pending);return r;}
 @Test void postListAndDetail_MapDataEmptyAndPaginationBoundaries(){Post p=post();when(posts.findAll(any(Specification.class),any(Pageable.class))).thenReturn(new PageImpl<>(List.of(p)));when(postReactions.countByPost_Id(1L)).thenReturn(3L);when(comments.countByPost_IdAndStatus(1L,CommentStatus.VISIBLE)).thenReturn(2L);assertThat(service.getPosts(" hello ",2L,3L,PostStatus.PUBLISHED,PostPrivacy.PUBLIC,LocalDateTime.now().minusDays(1),LocalDateTime.now(),0,999).getContent()).hasSize(1);ArgumentCaptor<Pageable> page=ArgumentCaptor.forClass(Pageable.class);verify(posts).findAll(any(Specification.class),page.capture());assertThat(page.getValue().getPageSize()).isEqualTo(100);when(posts.findById(1L)).thenReturn(Optional.of(p));assertThat(service.getPostDetail(1L).getReactionCount()).isEqualTo(3L);when(posts.findById(9L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getPostDetail(9L)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.getPosts(null,null,null,null,null,null,null,-1,1)).isInstanceOf(BadRequestException.class);}
 @Test void hideAndRestorePost_RecordActionsAndRejectDeleted(){Post p=post();when(posts.findById(1L)).thenReturn(Optional.of(p));when(users.findById(10L)).thenReturn(Optional.of(user(10)));ModerationActionRequest request=new ModerationActionRequest();request.setReason(" reason ");service.hidePost(principal,1L,request);assertThat(p.getStatus()).isEqualTo(PostStatus.HIDDEN);ArgumentCaptor<ModerationAction> captured=ArgumentCaptor.forClass(ModerationAction.class);verify(actions).save(captured.capture());assertThat(captured.getValue().getReason()).isEqualTo("reason");service.restorePost(principal,1L,null);assertThat(p.getStatus()).isEqualTo(PostStatus.PUBLISHED);p.setStatus(PostStatus.DELETED);assertThatThrownBy(()->service.hidePost(principal,1L,null)).isInstanceOf(BadRequestException.class);}
 @Test void commentListDetailHideAndRestore_CoverSuccessAndDeleted(){PostComment c=comment();when(comments.findAll(any(Specification.class),any(Pageable.class))).thenReturn(new PageImpl<>(List.of(c)));when(commentReactions.countByComment_Id(2L)).thenReturn(1L);when(comments.countByParentCommentIdAndStatus(2L,CommentStatus.VISIBLE)).thenReturn(2L);assertThat(service.getComments(" text ",1L,3L,CommentStatus.VISIBLE,null,null,0,1).getContent()).hasSize(1);when(comments.findById(2L)).thenReturn(Optional.of(c));when(users.findById(10L)).thenReturn(Optional.of(user(10)));service.hideComment(principal,2L,null);assertThat(c.getStatus()).isEqualTo(CommentStatus.HIDDEN);service.restoreComment(principal,2L,null);assertThat(c.getStatus()).isEqualTo(CommentStatus.VISIBLE);c.setStatus(CommentStatus.DELETED);assertThatThrownBy(()->service.restoreComment(principal,2L,null)).isInstanceOf(BadRequestException.class);when(comments.findById(9L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getCommentDetail(9L)).isInstanceOf(ResourceNotFoundException.class);}
 @Test void reportListDetailResolveAndReject_RecordActionsAndTargetModeration(){SocialReport postReport=report(SocialReport.ModerationTargetType.post);when(reports.findAll(any(Specification.class),any(Pageable.class))).thenReturn(new PageImpl<>(List.of(postReport)));assertThat(service.getReports(SocialReport.ReportStatus.pending,SocialReport.ModerationTargetType.post,SocialReport.ReportReason.spam,4L,1L,null,null,0,1).getContent()).hasSize(1);when(reports.findById(5L)).thenReturn(Optional.of(postReport));when(users.findById(10L)).thenReturn(Optional.of(user(10)));when(posts.findById(1L)).thenReturn(Optional.of(post()));ResolveSocialReportRequest resolve=new ResolveSocialReportRequest();resolve.setHideTarget(true);resolve.setResolutionNote(" done ");service.resolveReport(principal,5L,resolve);assertThat(postReport.getStatus()).isEqualTo(SocialReport.ReportStatus.resolved);verify(posts).save(any());verify(actions,times(2)).save(any());SocialReport commentReport=report(SocialReport.ModerationTargetType.comment);commentReport.setId(6L);when(reports.findById(6L)).thenReturn(Optional.of(commentReport));service.rejectReport(principal,6L,null);assertThat(commentReport.getStatus()).isEqualTo(SocialReport.ReportStatus.rejected);verify(reports,times(2)).save(any());}
 @Test void reportValidation_RejectsMissingAlreadyHandledAndUnknownModerator(){when(reports.findById(9L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getReportDetail(9L)).isInstanceOf(ResourceNotFoundException.class);SocialReport handled=report(SocialReport.ModerationTargetType.post);handled.setStatus(SocialReport.ReportStatus.resolved);when(reports.findById(5L)).thenReturn(Optional.of(handled));assertThatThrownBy(()->service.resolveReport(principal,5L,null)).isInstanceOf(BadRequestException.class);SocialReport pending=report(SocialReport.ModerationTargetType.post);when(reports.findById(6L)).thenReturn(Optional.of(pending));when(users.findById(10L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.rejectReport(principal,6L,null)).isInstanceOf(ResourceNotFoundException.class);when(posts.findById(1L)).thenReturn(Optional.of(post()));assertThatThrownBy(()->service.hidePost(null,1L,null)).isInstanceOf(BadRequestException.class);}
 @Test void listValidation_RejectsTimeRangeAndZeroSize(){LocalDateTime now=LocalDateTime.now();assertThatThrownBy(()->service.getReports(null,null,null,null,null,now,now.minusHours(1),0,1)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getComments(null,null,null,null,null,null,0,0)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getPostDetail(0L)).isInstanceOf(BadRequestException.class);}
 @SuppressWarnings({"unchecked","rawtypes"}) @Test void capturedSpecifications_ExecuteEveryFilterLambda(){when(posts.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());when(comments.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());when(reports.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());LocalDateTime now=LocalDateTime.now();service.getPosts("key",1L,2L,PostStatus.HIDDEN,PostPrivacy.PRIVATE,now.minusDays(1),now,0,1);service.getPosts(null,null,null,null,null,null,null,0,1);service.getComments("key",1L,2L,CommentStatus.HIDDEN,now.minusDays(1),now,0,1);service.getComments(null,null,null,null,null,null,0,1);service.getReports(SocialReport.ReportStatus.reviewing,SocialReport.ModerationTargetType.comment,SocialReport.ReportReason.other,1L,2L,now.minusDays(1),now,0,1);service.getReports(null,null,null,null,null,null,null,0,1);ArgumentCaptor<Specification> postSpec=ArgumentCaptor.forClass(Specification.class),commentSpec=ArgumentCaptor.forClass(Specification.class),reportSpec=ArgumentCaptor.forClass(Specification.class);verify(posts,times(2)).findAll(postSpec.capture(),any(Pageable.class));postSpec.getAllValues().forEach(this::execute);verify(comments,times(2)).findAll(commentSpec.capture(),any(Pageable.class));commentSpec.getAllValues().forEach(this::execute);verify(reports,times(2)).findAll(reportSpec.capture(),any(Pageable.class));reportSpec.getAllValues().forEach(this::execute);}
 @Test void successfulDetailsAndNullFilters_CoverMappingAndFalseSpecificationBranches(){Post p=post();PostComment c=comment();SocialReport r=report(SocialReport.ModerationTargetType.post);when(posts.findById(1L)).thenReturn(Optional.of(p));when(comments.findById(2L)).thenReturn(Optional.of(c));when(reports.findById(5L)).thenReturn(Optional.of(r));assertThat(service.getPostDetail(1L).getId()).isEqualTo(1L);assertThat(service.getCommentDetail(2L).getId()).isEqualTo(2L);assertThat(service.getReportDetail(5L).getId()).isEqualTo(5L);when(posts.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());when(comments.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());when(reports.findAll(any(Specification.class),any(Pageable.class))).thenReturn(Page.empty());service.getPosts(null,null,null,null,null,null,null,0,1);service.getComments("   ",null,null,null,null,null,0,1);service.getReports(null,null,null,null,null,null,null,0,1);}
 @Test void resolveWithoutHiding_AndReviewingStatus_RecordsSingleAction(){SocialReport r=report(SocialReport.ModerationTargetType.post);r.setStatus(SocialReport.ReportStatus.reviewing);when(reports.findById(5L)).thenReturn(Optional.of(r));when(users.findById(10L)).thenReturn(Optional.of(user(10)));service.resolveReport(principal,5L,null);assertThat(r.getStatus()).isEqualTo(SocialReport.ReportStatus.resolved);verify(actions,times(1)).save(any());verifyNoInteractions(posts,comments);}
 @Test void resolveCommentTargetAlreadyDeleted_SkipsTargetSaveButRecordsActions(){SocialReport r=report(SocialReport.ModerationTargetType.comment);PostComment deleted=comment();deleted.setStatus(CommentStatus.DELETED);when(reports.findById(5L)).thenReturn(Optional.of(r));when(comments.findById(2L)).thenReturn(Optional.of(deleted));when(users.findById(10L)).thenReturn(Optional.of(user(10)));ResolveSocialReportRequest request=new ResolveSocialReportRequest();request.setHideTarget(true);service.resolveReport(principal,5L,request);verify(comments,never()).save(deleted);verify(actions,times(2)).save(any());}
 @SuppressWarnings({"unchecked","rawtypes"}) private void execute(Specification specification){Root root=mock(Root.class);Path path=mock(Path.class);CriteriaBuilder cb=mock(CriteriaBuilder.class);Predicate predicate=mock(Predicate.class);when(root.get(anyString())).thenReturn(path);when(cb.lower(any())).thenReturn(mock(jakarta.persistence.criteria.Expression.class));when(cb.like(any(),anyString())).thenReturn(predicate);when(cb.equal(any(),any())).thenReturn(predicate);when(cb.greaterThanOrEqualTo(any(jakarta.persistence.criteria.Expression.class),any(LocalDateTime.class))).thenReturn(predicate);when(cb.lessThanOrEqualTo(any(jakarta.persistence.criteria.Expression.class),any(LocalDateTime.class))).thenReturn(predicate);when(cb.and(any(Predicate[].class))).thenReturn(predicate);specification.toPredicate(root,null,cb);}
}
