package com.petcare.backend.service.impl;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.petcare.backend.exception.*;import com.petcare.backend.model.*;import com.petcare.backend.repository.*;import com.petcare.backend.security.UserPrincipal;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.*;import org.mockito.junit.jupiter.*;import org.springframework.data.domain.*;
@ExtendWith(MockitoExtension.class) @MockitoSettings(strictness=org.mockito.quality.Strictness.LENIENT) class BlogServiceImplTest {@Mock BlogRepository blogs;@Mock BlogSaveRepository saves;@Mock UserRepository users;@Mock UserPrincipal principal;BlogServiceImpl service;@BeforeEach void init(){service=new BlogServiceImpl(blogs,saves,users);when(principal.getId()).thenReturn(1L);} Blog blog(){Blog b=new Blog();b.setId(2L);b.setTitle("Title");b.setContent("Content");b.setCategory(Blog.BlogCategory.health);b.setStatus(Blog.BlogStatus.published);User u=new User();u.setId(9L);u.setFullName("Admin");b.setAuthor(u);return b;}
@Test void categoriesAndPublishedListCoverKeywordSavedAndPagination(){assertThat(service.getBlogCategories()).hasSize(5).extracting("value").contains("health","vaccination");Blog b=blog();when(blogs.searchPublished(eq(Blog.BlogStatus.published),eq("dog"),eq(Blog.BlogCategory.health),any())).thenReturn(new PageImpl<>(List.of(b)));when(saves.existsByBlog_IdAndUser_Id(2L,1L)).thenReturn(true);var out=service.getPublishedBlogs(principal,"  dog  ",Blog.BlogCategory.health,2,99);assertThat(out.getContent()).singleElement().satisfies(r->{assertThat(r.getContent()).isNull();assertThat(r.getSavedByCurrentUser()).isTrue();});ArgumentCaptor<Pageable> p=ArgumentCaptor.forClass(Pageable.class);verify(blogs).searchPublished(eq(Blog.BlogStatus.published),eq("dog"),eq(Blog.BlogCategory.health),p.capture());assertThat(p.getValue().getPageSize()).isEqualTo(50);assertThatThrownBy(()->service.getPublishedBlogs(principal,null,null,-1,1)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getPublishedBlogs(principal,null,null,0,0)).isInstanceOf(BadRequestException.class);}
@Test void detailHandlesMissingAndSavedNullUserId(){when(blogs.findByIdAndStatus(2L,Blog.BlogStatus.published)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getPublishedBlogDetail(principal,2L)).isInstanceOf(ResourceNotFoundException.class);Blog b=blog();when(blogs.findByIdAndStatus(2L,Blog.BlogStatus.published)).thenReturn(Optional.of(b));when(principal.getId()).thenReturn(null);var r=service.getPublishedBlogDetail(principal,2L);assertThat(r.getContent()).isEqualTo("Content");assertThat(r.getSavedByCurrentUser()).isFalse();verifyNoInteractions(saves);}
@Test void saveCoversMissingAlreadySavedUserMissingAndSuccess(){when(blogs.findByIdAndStatus(2L,Blog.BlogStatus.published)).thenReturn(Optional.empty());assertThatThrownBy(()->service.saveBlog(principal,2L)).isInstanceOf(ResourceNotFoundException.class);Blog b=blog();when(blogs.findByIdAndStatus(2L,Blog.BlogStatus.published)).thenReturn(Optional.of(b));when(saves.existsByBlog_IdAndUser_Id(2L,1L)).thenReturn(true);assertThat(service.saveBlog(principal,2L).getSavedByCurrentUser()).isTrue();verify(saves,never()).save(any());when(saves.existsByBlog_IdAndUser_Id(2L,1L)).thenReturn(false);when(users.findById(1L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.saveBlog(principal,2L)).isInstanceOf(ResourceNotFoundException.class);User u=new User();u.setId(1L);when(users.findById(1L)).thenReturn(Optional.of(u));service.saveBlog(principal,2L);verify(saves).save(argThat(s->s.getBlog()==b&&s.getUser()==u));}
@Test void unsaveAndSavedListCoverOptionalAndPage(){BlogSave save=new BlogSave();when(saves.findByBlog_IdAndUser_Id(2L,1L)).thenReturn(Optional.of(save));service.unsaveBlog(principal,2L);verify(saves).delete(save);when(saves.findByBlog_IdAndUser_Id(3L,1L)).thenReturn(Optional.empty());service.unsaveBlog(principal,3L);BlogSave entry=new BlogSave();entry.setBlog(blog());when(saves.findByUser_IdOrderByCreatedAtDesc(eq(1L),any())).thenReturn(new PageImpl<>(List.of(entry)));assertThat(service.getSavedBlogs(principal,0,1).getContent()).singleElement().satisfies(r->assertThat(r.getSavedByCurrentUser()).isTrue());}
}
