package com.petcare.backend.service.impl;

import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;
import com.petcare.backend.dto.friend.request.SendFriendRequestRequest;
import com.petcare.backend.exception.*;
import com.petcare.backend.model.*;
import com.petcare.backend.model.enums.FriendRequestStatus;
import com.petcare.backend.repository.*;
import com.petcare.backend.service.FriendMapper;
import java.util.Optional;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.*;

@ExtendWith(MockitoExtension.class) @MockitoSettings(strictness=org.mockito.quality.Strictness.LENIENT)
class FriendServiceImplTest {
 @Mock FriendRequestRepository requests;@Mock FriendshipRepository friendships;@Mock UserRepository users;@Mock NotificationRepository notifications;@Mock FriendMapper mapper;FriendServiceImpl service;
 @BeforeEach void init(){service=new FriendServiceImpl(requests,friendships,users,notifications,mapper);when(requests.save(any())).thenAnswer(i->i.getArgument(0));}
 User user(long id){User u=new User();u.setId(id);u.setStatus("active");u.setFullName("U"+id);return u;}
 @Test void sendRequest_ValidationsAndDuplicatePartitions(){User a=user(1),b=user(2);when(users.findById(1L)).thenReturn(Optional.of(a));SendFriendRequestRequest r=new SendFriendRequestRequest();assertThatThrownBy(()->service.sendFriendRequest(1L,r)).isInstanceOf(BadRequestException.class);r.setReceiverId(1L);assertThatThrownBy(()->service.sendFriendRequest(1L,r)).isInstanceOf(BadRequestException.class);r.setReceiverId(2L);when(users.findById(2L)).thenReturn(Optional.of(b));when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(true);assertThatThrownBy(()->service.sendFriendRequest(1L,r)).isInstanceOf(ConflictException.class);when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(false);FriendRequest pending=FriendRequest.builder().sender(a).receiver(b).status(FriendRequestStatus.PENDING).build();when(requests.findBySender_IdAndReceiver_Id(1L,2L)).thenReturn(Optional.of(pending));service.sendFriendRequest(1L,r);verify(mapper).toFriendRequestResponse(pending);}
 @Test void unfriend_IdAndMissingUserPartitions(){when(users.findById(1L)).thenReturn(Optional.of(user(1)));assertThatThrownBy(()->service.unfriend(1L,0L)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.unfriend(1L,1L)).isInstanceOf(BadRequestException.class);when(users.existsById(2L)).thenReturn(false);assertThatThrownBy(()->service.unfriend(1L,2L)).isInstanceOf(ResourceNotFoundException.class);when(users.existsById(2L)).thenReturn(true);service.unfriend(1L,2L);verify(friendships).deleteFriendshipBetween(1L,2L);}
 @Test void acceptDeclineCancel_RequestPermissionAndStatusBranches(){User sender=user(1),receiver=user(2);when(users.findById(2L)).thenReturn(Optional.of(receiver));FriendRequest request=FriendRequest.builder().sender(sender).receiver(receiver).status(FriendRequestStatus.PENDING).build();when(requests.findById(9L)).thenReturn(Optional.of(request));when(users.findById(1L)).thenReturn(Optional.of(sender));service.acceptFriendRequest(2L,9L);verify(friendships).save(any());request.setStatus(FriendRequestStatus.PENDING);service.declineFriendRequest(2L,9L);request.setStatus(FriendRequestStatus.PENDING);service.cancelFriendRequest(1L,9L);request.setStatus(FriendRequestStatus.ACCEPTED);assertThatThrownBy(()->service.declineFriendRequest(2L,9L)).isInstanceOf(ConflictException.class);assertThatThrownBy(()->service.cancelFriendRequest(2L,9L)).isInstanceOf(ForbiddenException.class);}
 @Test void friendshipStatus_SelfFriendsPendingHistoryAndNone(){User a=user(1),b=user(2);when(users.findById(1L)).thenReturn(Optional.of(a));when(users.existsById(1L)).thenReturn(true);when(users.existsById(2L)).thenReturn(true);service.getFriendshipStatus(1L,1L);when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(true);service.getFriendshipStatus(1L,2L);when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(false);FriendRequest outgoing=FriendRequest.builder().id(7L).status(FriendRequestStatus.PENDING).build();when(requests.findBySender_IdAndReceiver_IdAndStatus(1L,2L,FriendRequestStatus.PENDING)).thenReturn(Optional.of(outgoing));service.getFriendshipStatus(1L,2L);when(requests.findBySender_IdAndReceiver_IdAndStatus(1L,2L,FriendRequestStatus.PENDING)).thenReturn(Optional.empty());when(requests.findBySender_IdAndReceiver_IdAndStatus(2L,1L,FriendRequestStatus.PENDING)).thenReturn(Optional.empty());when(requests.findBetweenOrderByUpdatedAtDesc(1L,2L)).thenReturn(java.util.List.of());service.getFriendshipStatus(1L,2L);}
 @Test void requestPages_PaginationBoundaries_AreValidated(){when(users.findById(1L)).thenReturn(Optional.of(user(1)));assertThatThrownBy(()->service.getIncomingRequests(1L,-1,1)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getOutgoingRequests(1L,0,0)).isInstanceOf(BadRequestException.class);}
 @Test void friendshipStatus_IncomingDeclinedAndCancelled_AreMapped(){when(users.findById(1L)).thenReturn(Optional.of(user(1)));when(users.existsById(2L)).thenReturn(true);when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(false);when(requests.findBySender_IdAndReceiver_IdAndStatus(1L,2L,FriendRequestStatus.PENDING)).thenReturn(Optional.empty());FriendRequest incoming=FriendRequest.builder().id(8L).status(FriendRequestStatus.PENDING).build();when(requests.findBySender_IdAndReceiver_IdAndStatus(2L,1L,FriendRequestStatus.PENDING)).thenReturn(Optional.of(incoming));service.getFriendshipStatus(1L,2L);when(requests.findBySender_IdAndReceiver_IdAndStatus(2L,1L,FriendRequestStatus.PENDING)).thenReturn(Optional.empty());FriendRequest declined=FriendRequest.builder().id(9L).status(FriendRequestStatus.DECLINED).build();when(requests.findBetweenOrderByUpdatedAtDesc(1L,2L)).thenReturn(java.util.List.of(declined));service.getFriendshipStatus(1L,2L);declined.setStatus(FriendRequestStatus.CANCELLED);service.getFriendshipStatus(1L,2L);}
 @Test void areFriends_NullSelfAndRepositoryPartitions(){assert(!service.areFriends(null,2L));assert(!service.areFriends(1L,null));assert(!service.areFriends(1L,1L));when(friendships.existsFriendshipBetween(1L,2L)).thenReturn(true);assert(service.areFriends(1L,2L));}
 @Test void requestLifecycle_MissingRequestIsRejectedForAllActions(){when(users.findById(1L)).thenReturn(Optional.of(user(1)));when(requests.findById(9L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.acceptFriendRequest(1L,9L)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.declineFriendRequest(1L,9L)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.cancelFriendRequest(1L,9L)).isInstanceOf(ResourceNotFoundException.class);}
 @Test void requestLifecycle_WrongActorAndNonPending_AreRejected(){User sender=user(1),receiver=user(2);when(users.findById(1L)).thenReturn(Optional.of(sender));when(users.findById(2L)).thenReturn(Optional.of(receiver));FriendRequest r=FriendRequest.builder().sender(sender).receiver(receiver).status(FriendRequestStatus.PENDING).build();when(requests.findById(9L)).thenReturn(Optional.of(r));assertThatThrownBy(()->service.acceptFriendRequest(1L,9L)).isInstanceOf(ForbiddenException.class);assertThatThrownBy(()->service.cancelFriendRequest(2L,9L)).isInstanceOf(ForbiddenException.class);r.setStatus(FriendRequestStatus.ACCEPTED);assertThatThrownBy(()->service.acceptFriendRequest(2L,9L)).isInstanceOf(ConflictException.class);assertThatThrownBy(()->service.cancelFriendRequest(1L,9L)).isInstanceOf(ConflictException.class);}
 @Test void sendRequest_ReverseAndAcceptedExisting_AreHandled(){User a=user(1),b=user(2);when(users.findById(1L)).thenReturn(Optional.of(a));when(users.findById(2L)).thenReturn(Optional.of(b));SendFriendRequestRequest input=new SendFriendRequestRequest();input.setReceiverId(2L);FriendRequest reverse=FriendRequest.builder().sender(b).receiver(a).status(FriendRequestStatus.PENDING).build();when(requests.findBySender_IdAndReceiver_IdAndStatus(2L,1L,FriendRequestStatus.PENDING)).thenReturn(Optional.of(reverse));assertThatThrownBy(()->service.sendFriendRequest(1L,input)).isInstanceOf(ConflictException.class);when(requests.findBySender_IdAndReceiver_IdAndStatus(2L,1L,FriendRequestStatus.PENDING)).thenReturn(Optional.empty());FriendRequest accepted=FriendRequest.builder().sender(a).receiver(b).status(FriendRequestStatus.ACCEPTED).build();when(requests.findBySender_IdAndReceiver_Id(1L,2L)).thenReturn(Optional.of(accepted));assertThatThrownBy(()->service.sendFriendRequest(1L,input)).isInstanceOf(ConflictException.class);}
 @Test void inactiveMissingTargetAndNullSender_PartitionsAreRejected(){User inactive=user(1);inactive.setStatus("inactive");when(users.findById(1L)).thenReturn(Optional.of(inactive));assertThatThrownBy(()->service.getIncomingRequests(1L,0,1)).isInstanceOf(ForbiddenException.class);when(users.findById(1L)).thenReturn(Optional.of(user(1)));when(users.existsById(2L)).thenReturn(false);assertThatThrownBy(()->service.getUserFriends(1L,2L,0,1)).isInstanceOf(ResourceNotFoundException.class);FriendRequest request=FriendRequest.builder().status(FriendRequestStatus.PENDING).build();when(requests.findById(9L)).thenReturn(Optional.of(request));assertThatThrownBy(()->service.cancelFriendRequest(1L,9L)).isInstanceOf(ForbiddenException.class);}
}
