package com.petcare.backend.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.petcare.backend.dto.pet.request.CreatePetRequest;
import com.petcare.backend.dto.pet.request.UpdatePetRequest;
import com.petcare.backend.exception.BadRequestException;
import com.petcare.backend.exception.ForbiddenException;
import com.petcare.backend.model.*;
import com.petcare.backend.repository.*;
import com.petcare.backend.security.UserPrincipal;
import com.petcare.backend.service.FileStorageService;
import com.petcare.backend.service.NotificationService;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@ExtendWith(MockitoExtension.class) @MockitoSettings(strictness=Strictness.LENIENT)
class PetServiceImplTest {
 @Mock PetRepository pets;@Mock UserRepository users;@Mock SpeciesRepository species;@Mock BreedRepository breeds;@Mock PetCoParentRepository coParents;@Mock CoParentInvitationRepository invitations;@Mock WeightLogRepository weights;@Mock HealthConditionRepository conditions;@Mock PetTimelineEventRepository timeline;@Mock FileStorageService files;@Mock NotificationService notifications;@Mock PetVaccinationRepository vaccinations;@Mock VaccineTemplateRepository templates;@Mock UserPrincipal principal;PetServiceImpl service;static final long U=1L,P=2L,S=3L;
 @BeforeEach void setUp(){service=new PetServiceImpl(pets,users,species,breeds,coParents,invitations,weights,conditions,timeline,files,notifications,vaccinations,templates);when(principal.getId()).thenReturn(U);when(pets.save(any())).thenAnswer(i->{Pet p=i.getArgument(0);p.setId(P);return p;});}
 User user(long id){User u=new User();u.setId(id);u.setStatus("active");u.setFullName("Owner");return u;} Pet pet(long owner){Pet p=new Pet();p.setId(P);p.setOwner(user(owner));p.setName("Milo");p.setStatus(Pet.PetStatus.active);return p;} CreatePetRequest request(){CreatePetRequest r=new CreatePetRequest();r.setName(" Milo ");r.setSpeciesId(S);r.setDateOfBirth(LocalDate.now());r.setCurrentWeight(new BigDecimal("0.01"));return r;}
 @Test void createPet_ValidWithSpeciesWeightAndConditions_PersistsInitialRecords(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Species s=new Species();s.setId(S);when(species.findById(S)).thenReturn(Optional.of(s));CreatePetRequest r=request();r.setAllergies(List.of("dust"," "));service.createPet(principal,r);verify(pets).save(any());verify(weights).save(any());verify(conditions).save(any());verify(timeline).save(any());}
 @Test void createPet_UserSpeciesAndBreedPartitions_AreValidated(){when(users.findById(U)).thenReturn(Optional.empty());assertThatThrownBy(()->service.createPet(principal,request())).isInstanceOf(BadRequestException.class);when(users.findById(U)).thenReturn(Optional.of(user(U)));when(species.findById(S)).thenReturn(Optional.empty());assertThatThrownBy(()->service.createPet(principal,request())).isInstanceOf(BadRequestException.class);CreatePetRequest r=request();r.setBreedId(9L);Species selected=new Species();selected.setId(S);when(species.findById(S)).thenReturn(Optional.of(selected));Breed b=new Breed();Species other=new Species();other.setId(8L);b.setSpecies(other);when(breeds.findById(9L)).thenReturn(Optional.of(b));assertThatThrownBy(()->service.createPet(principal,r)).isInstanceOf(BadRequestException.class);}
 @Test void getAndUpdatePet_OwnerViewerAndMissingPartitions(){Pet p=pet(U);when(pets.findByIdAndAccessibleByUserId(P,U)).thenReturn(Optional.of(p));assertThat(service.getPetById(principal,P)).isNotNull();UpdatePetRequest update=new UpdatePetRequest();update.setName(" New ");service.updatePet(principal,P,update);assertThat(p.getName()).isEqualTo("New");when(pets.findByIdAndAccessibleByUserId(P,U)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getPetById(principal,P)).isInstanceOf(BadRequestException.class);when(pets.findByIdAndAccessibleByUserId(P,U)).thenReturn(Optional.of(pet(9L)));when(coParents.findByPetIdAndUserId(P,U)).thenReturn(Optional.empty());assertThatThrownBy(()->service.updatePet(principal,P,new UpdatePetRequest())).isInstanceOf(ForbiddenException.class);}
 @Test void archiveAndDelete_OwnerInactiveAndOtherUserPartitions(){Pet p=pet(U);when(pets.findById(P)).thenReturn(Optional.of(p));assertThat(service.archivePet(principal,P)).isNotNull();assertThat(p.getStatus()).isEqualTo(Pet.PetStatus.archived);service.deletePet(principal,P);verify(pets).delete(p);Pet deceased=pet(U);deceased.setStatus(Pet.PetStatus.deceased);when(pets.findById(P)).thenReturn(Optional.of(deceased));assertThatThrownBy(()->service.archivePet(principal,P)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);when(pets.findById(P)).thenReturn(Optional.of(pet(9L)));assertThatThrownBy(()->service.deletePet(principal,P)).isInstanceOf(BadRequestException.class);}
 @Test void invitationPages_InvalidBoundaries_AreRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));assertThatThrownBy(()->service.getIncomingInvitations(U,-1,1)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getOutgoingInvitations(U,0,0)).isInstanceOf(BadRequestException.class);}
 @Test void invitation_NotFoundAndWrongInvitee_AreRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(invitations.findById(9L)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ResourceNotFoundException.class);CoParentInvitation item=new CoParentInvitation();item.setInviteeUser(user(8L));when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.acceptCoParentInvitation(U,9L)).isInstanceOf(ForbiddenException.class);}
 @Test void acceptInvitation_ExpiredPendingInvitation_IsRejectedBeforeCoParentCreation(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setInviteeUser(user(U));item.setStatus(CoParentInvitation.InvitationStatus.pending);item.setExpiresAt(java.time.LocalDateTime.now().minusMinutes(1));when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.acceptCoParentInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
 @Test void acceptInvitation_InactivePet_IsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Pet inactive=pet(8L);inactive.setStatus(Pet.PetStatus.archived);CoParentInvitation item=new CoParentInvitation();item.setInviteeUser(user(U));item.setPet(inactive);item.setStatus(CoParentInvitation.InvitationStatus.pending);item.setExpiresAt(java.time.LocalDateTime.now().plusMinutes(5));when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.acceptCoParentInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
 @Test void acceptInvitation_ExistingCoParent_IsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setInviteeUser(user(U));item.setPet(pet(8L));item.setStatus(CoParentInvitation.InvitationStatus.pending);item.setExpiresAt(java.time.LocalDateTime.now().plusMinutes(5));when(invitations.findById(9L)).thenReturn(Optional.of(item));when(coParents.existsByPetIdAndUserId(P,U)).thenReturn(true);assertThatThrownBy(()->service.acceptCoParentInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
 @Test void revokeInvitation_UnauthorizedCaller_IsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setInviter(user(8L));item.setPet(pet(9L));when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.revokeCoParentInvitation(U,9L)).isInstanceOf(ForbiddenException.class);}
 @Test void revokeInvitation_NonPending_IsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setInviter(user(U));item.setPet(pet(U));item.setStatus(CoParentInvitation.InvitationStatus.accepted);when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.revokeCoParentInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
 @Test void revokeInvitation_PendingWithNullInvitee_RevokesWithoutNotification(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setId(9L);item.setInviter(user(U));item.setPet(pet(U));item.setStatus(CoParentInvitation.InvitationStatus.pending);item.setInviteeEmail("x@y.com");when(invitations.findById(9L)).thenReturn(Optional.of(item));when(invitations.save(item)).thenReturn(item);service.revokeCoParentInvitation(U,9L);assertThat(item.getStatus()).isEqualTo(CoParentInvitation.InvitationStatus.revoked);verify(notifications,org.mockito.Mockito.never()).createNotification(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());}
 @Test void revokeInvitation_PendingWithInvitee_NotifiesInvitee(){when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setId(9L);item.setInviter(user(U));item.setPet(pet(U));item.setInviteeUser(user(8L));item.setStatus(CoParentInvitation.InvitationStatus.pending);when(invitations.findById(9L)).thenReturn(Optional.of(item));when(invitations.save(item)).thenReturn(item);service.revokeCoParentInvitation(U,9L);verify(notifications).createNotification(org.mockito.ArgumentMatchers.eq(8L),org.mockito.ArgumentMatchers.eq(U),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.eq("co_parent_revoked"),org.mockito.ArgumentMatchers.eq(9L));}
 @Test void createInvitation_InactivePetAndNonOwner_AreRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest r=new com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest();r.setInviteeEmail("x@y.com");r.setRole("editor");Pet inactive=pet(U);inactive.setStatus(Pet.PetStatus.archived);when(pets.findById(P)).thenReturn(Optional.of(inactive));assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);when(pets.findById(P)).thenReturn(Optional.of(pet(8L)));assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(ForbiddenException.class);}
 @Test void createInvitation_InviteePartitions_AreRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(pets.findById(P)).thenReturn(Optional.of(pet(U)));com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest r=new com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest();r.setInviteeEmail("x@y.com");r.setRole("editor");User inactive=user(8L);inactive.setStatus("inactive");when(users.findByEmail("x@y.com")).thenReturn(Optional.of(inactive));assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);when(users.findByEmail("x@y.com")).thenReturn(Optional.of(user(U)));assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(BadRequestException.class);when(users.findByEmail("x@y.com")).thenReturn(Optional.of(user(8L)));when(coParents.existsByPetIdAndUserId(P,8L)).thenReturn(true);assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);when(coParents.existsByPetIdAndUserId(P,8L)).thenReturn(false);when(invitations.existsByPetIdAndInviteeUserIdAndStatus(P,8L,CoParentInvitation.InvitationStatus.pending)).thenReturn(true);assertThatThrownBy(()->service.createCoParentInvitation(U,P,r)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
 @Test void createInvitation_ValidOwnerInvitee_PersistsAndNotifies(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(pets.findById(P)).thenReturn(Optional.of(pet(U)));when(users.findByEmail("x@y.com")).thenReturn(Optional.of(user(8L)));when(invitations.save(any())).thenAnswer(i->{CoParentInvitation x=i.getArgument(0);x.setId(9L);return x;});com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest r=new com.petcare.backend.dto.pet.request.CreateCoParentInvitationRequest();r.setInviteeEmail("x@y.com");r.setRole("editor");assertThat(service.createCoParentInvitation(U,P,r).getRole()).isEqualTo("editor");verify(notifications).createNotification(org.mockito.ArgumentMatchers.eq(8L),org.mockito.ArgumentMatchers.eq(U),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.eq("co_parent_invite"),org.mockito.ArgumentMatchers.eq(9L));}
 @Test void createPet_VaccineTemplatesActiveAndInactive_GeneratesOnlyActiveSchedule(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Species s=new Species();s.setId(S);when(species.findById(S)).thenReturn(Optional.of(s));VaccineTemplate active=new VaccineTemplate();active.setActive(true);active.setVaccineName("A");active.setDoseNumber(1);active.setRecommendedAgeWeeks(2);VaccineTemplate inactive=new VaccineTemplate();inactive.setActive(false);when(templates.findBySpeciesId(S)).thenReturn(List.of(active,inactive));CreatePetRequest r=request();r.setDateOfBirth(null);r.setEstimatedAgeMonths(2);service.createPet(principal,r);verify(vaccinations).save(any());}
 @Test void updateCoParentRole_SameAndChangedRole_AreHandled(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(pets.findById(P)).thenReturn(Optional.of(pet(U)));PetCoParent cp=new PetCoParent();cp.setPet(pet(U));cp.setUser(user(8L));cp.setInvitedBy(user(U));cp.setRole(PetCoParent.CoParentRole.editor);when(coParents.findByIdAndPetId(3L,P)).thenReturn(Optional.of(cp));com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest same=new com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest();same.setRole("editor");assertThat(service.updateCoParentRole(U,P,3L,same).getRole()).isEqualTo("editor");com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest changed=new com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest();changed.setRole("viewer");when(coParents.save(cp)).thenReturn(cp);service.updateCoParentRole(U,P,3L,changed);verify(notifications).createNotification(org.mockito.ArgumentMatchers.eq(8L),org.mockito.ArgumentMatchers.eq(U),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.eq("co_parent_role_updated"),org.mockito.ArgumentMatchers.eq(P));}
 @Test void createPet_AllOptionalFields_AppliesPetDataBranches(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Species s=new Species();s.setId(S);when(species.findById(S)).thenReturn(Optional.of(s));CreatePetRequest r=request();r.setGender(Pet.Gender.female);r.setEstimatedAgeMonths(0);r.setColorFeatures("brown");r.setSpayedStatus(Pet.SpayedStatus.spayed);r.setNotes("note");r.setStatus(Pet.PetStatus.active);service.createPet(principal,r);verify(pets).save(any());}
 @Test void createPet_CustomBreedWithoutBreed_IsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Species s=new Species();s.setId(S);when(species.findById(S)).thenReturn(Optional.of(s));CreatePetRequest r=request();r.setCustomBreedName("mixed");assertThatThrownBy(()->service.createPet(principal,r)).isInstanceOf(BadRequestException.class);}
 @Test void createPet_BreedWithoutSpecies_IsAllowedWhenBreedExists(){when(users.findById(U)).thenReturn(Optional.of(user(U)));Breed b=new Breed();Species s=new Species();s.setId(S);b.setSpecies(s);when(breeds.findById(9L)).thenReturn(Optional.of(b));CreatePetRequest r=request();r.setSpeciesId(null);r.setBreedId(9L);service.createPet(principal,r);verify(pets).save(any());}
 @Test void getInvitation_InviterInviteeAndUnauthorizedPartitions(){User inviter=user(U),invitee=user(8L),other=user(9L);when(users.findById(U)).thenReturn(Optional.of(inviter));when(users.findById(8L)).thenReturn(Optional.of(invitee));when(users.findById(9L)).thenReturn(Optional.of(other));CoParentInvitation item=new CoParentInvitation();item.setId(9L);item.setPet(pet(U));item.setInviter(inviter);item.setInviteeUser(invitee);item.setInviteeEmail("x@y.com");item.setRole(PetCoParent.CoParentRole.editor);item.setStatus(CoParentInvitation.InvitationStatus.pending);when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThat(service.getInvitation(U,9L).getInviterId()).isEqualTo(U);assertThat(service.getInvitation(8L,9L).getInviteeUserId()).isEqualTo(8L);assertThatThrownBy(()->service.getInvitation(9L,9L)).isInstanceOf(ForbiddenException.class);}
 @Test void archivePet_NotOwnerAlreadyArchivedAndNotFound_AreHandled(){Pet other=pet(8L);when(pets.findById(P)).thenReturn(Optional.of(other));assertThatThrownBy(()->service.archivePet(principal,P)).isInstanceOf(ForbiddenException.class);Pet archived=pet(U);archived.setStatus(Pet.PetStatus.archived);when(pets.findById(P)).thenReturn(Optional.of(archived));assertThat(service.archivePet(principal,P)).isNotNull();when(pets.findById(P)).thenReturn(Optional.empty());assertThatThrownBy(()->service.archivePet(principal,P)).isInstanceOf(com.petcare.backend.exception.ResourceNotFoundException.class);}
 @Test void updateCoParentRole_OwnerHelperMissingInactiveAndUnauthorized_AreRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(pets.findById(P)).thenReturn(Optional.empty());com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest r=new com.petcare.backend.dto.pet.request.UpdateCoParentRoleRequest();r.setRole("viewer");assertThatThrownBy(()->service.updateCoParentRole(U,P,3L,r)).isInstanceOf(com.petcare.backend.exception.ResourceNotFoundException.class);Pet inactive=pet(U);inactive.setStatus(Pet.PetStatus.archived);when(pets.findById(P)).thenReturn(Optional.of(inactive));assertThatThrownBy(()->service.updateCoParentRole(U,P,3L,r)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);when(pets.findById(P)).thenReturn(Optional.of(pet(8L)));assertThatThrownBy(()->service.updateCoParentRole(U,P,3L,r)).isInstanceOf(ForbiddenException.class);}
 @Test void removeCoParent_SuccessNotifiesAndMissingTargetIsRejected(){when(users.findById(U)).thenReturn(Optional.of(user(U)));when(pets.findById(P)).thenReturn(Optional.of(pet(U)));PetCoParent cp=new PetCoParent();cp.setUser(user(8L));when(coParents.findByIdAndPetId(3L,P)).thenReturn(Optional.of(cp));service.removeCoParent(U,P,3L);verify(coParents).delete(cp);verify(notifications).createNotification(org.mockito.ArgumentMatchers.eq(8L),org.mockito.ArgumentMatchers.eq(U),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.eq("co_parent_removed"),org.mockito.ArgumentMatchers.eq(P));when(coParents.findByIdAndPetId(3L,P)).thenReturn(Optional.empty());assertThatThrownBy(()->service.removeCoParent(U,P,3L)).isInstanceOf(com.petcare.backend.exception.ResourceNotFoundException.class);}
 @Test void getPet_ResponseMapsAllergyAndChronicConditions(){Pet p=pet(U);when(pets.findByIdAndAccessibleByUserId(P,U)).thenReturn(Optional.of(p));HealthCondition allergy=new HealthCondition();allergy.setType(HealthCondition.ConditionType.allergy);allergy.setTitle("dust");HealthCondition chronic=new HealthCondition();chronic.setType(HealthCondition.ConditionType.chronic_disease);chronic.setTitle("skin");when(conditions.findByPetIdAndIsActiveTrue(P)).thenReturn(List.of(allergy,chronic));assertThat(service.getPetById(principal,P).getAllergies()).contains("dust");assertThat(service.getPetById(principal,P).getMedicalConditions()).contains("skin");}
 @Test void invitationHelpers_InactiveUserAndNonPending_AreRejected(){User inactive=user(U);inactive.setStatus("inactive");when(users.findById(U)).thenReturn(Optional.of(inactive));assertThatThrownBy(()->service.getIncomingInvitations(U,0,1)).isInstanceOf(BadRequestException.class);when(users.findById(U)).thenReturn(Optional.of(user(U)));CoParentInvitation item=new CoParentInvitation();item.setInviteeUser(user(U));item.setStatus(CoParentInvitation.InvitationStatus.accepted);when(invitations.findById(9L)).thenReturn(Optional.of(item));assertThatThrownBy(()->service.declineCoParentInvitation(U,9L)).isInstanceOf(com.petcare.backend.exception.ConflictException.class);}
}
