package com.petcare.backend.service.impl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.petcare.backend.dto.post.request.CreatePostMediaRequest;
import com.petcare.backend.dto.post.request.CreatePostRequest;
import com.petcare.backend.dto.post.request.UpdatePostRequest;
import com.petcare.backend.dto.post.response.PostResponse;
import com.petcare.backend.dto.post.response.PostCommentResponse;
import com.petcare.backend.dto.upload.UploadFileResponse;
import com.petcare.backend.exception.BadRequestException;
import com.petcare.backend.exception.ResourceNotFoundException;
import com.petcare.backend.model.Post;
import com.petcare.backend.model.User;
import com.petcare.backend.model.enums.PostPrivacy;
import com.petcare.backend.model.enums.PostStatus;
import com.petcare.backend.model.enums.CommentStatus;
import com.petcare.backend.repository.*;
import com.petcare.backend.service.*;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.quality.Strictness;
import org.mockito.junit.jupiter.MockitoSettings;
import org.springframework.data.domain.PageImpl;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class PostServiceImplTest {
    static final long USER=7L, POST=11L, PET=3L;
    @Mock PetRepository petRepository; @Mock PostRepository postRepository; @Mock PostMediaRepository postMediaRepository; @Mock PostReactionRepository postReactionRepository; @Mock PostCommentRepository postCommentRepository; @Mock PostSaveRepository postSaveRepository; @Mock CommentMediaRepository commentMediaRepository; @Mock CommentReactionRepository commentReactionRepository; @Mock UserRepository userRepository; @Mock FileStorageService fileStorageService; @Mock FriendService friendService; @Mock PostMapper postMapper; @Mock SocialPermissionService socialPermissionService; @Mock PetTagPermissionService petTagPermissionService; @Mock PetTimelineService petTimelineService;
    PostServiceImpl service;
    @BeforeEach void setUp() {
        service=new PostServiceImpl(petRepository,postRepository,postMediaRepository,postReactionRepository,postCommentRepository,postSaveRepository,commentMediaRepository,commentReactionRepository,userRepository,fileStorageService,friendService,postMapper,socialPermissionService,petTagPermissionService,petTimelineService);
        when(postRepository.save(any())).thenAnswer(i->{Post p=i.getArgument(0); if(p.getId()==null)p.setId(POST); return p;});
        when(postMapper.toPostResponse(any(),anyList(),anyList(),any(),org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyBoolean(),any())).thenReturn(new PostResponse());
    }
    private User user(){User u=new User();u.setId(USER);return u;} private Post post(){return Post.builder().id(POST).user(user()).caption("old").privacy(PostPrivacy.PUBLIC).status(PostStatus.PUBLISHED).commentsLocked(false).build();}
    private void active(){when(userRepository.findById(USER)).thenReturn(Optional.of(user()));} private void existing(Post p){when(postRepository.findByIdAndStatusNot(POST,PostStatus.DELETED)).thenReturn(Optional.of(p));}
    private CreatePostRequest create(String caption){CreatePostRequest r=new CreatePostRequest();r.setCaption(caption);r.setPrivacy("public");return r;}
    private CreatePostMediaRequest media(){CreatePostMediaRequest m=new CreatePostMediaRequest();m.setMediaUrl(" https://x ");m.setMediaType("image");return m;}

    @Test void createPost_CaptionOnly_StoresPublishedTrimmedPost() { active(); var r=create(" text "); service.createPost(r,USER); verify(postRepository).save(org.mockito.ArgumentMatchers.argThat(p->p.getCaption().equals("text")&&p.getStatus()==PostStatus.PUBLISHED)); }
    @Test void createPost_MediaOnlyAndTaggedPet_CreatesMediaAndTimeline() { active(); var r=create(" ");r.setPetId(PET);r.setMedia(List.of(media())); com.petcare.backend.model.Pet pet=new com.petcare.backend.model.Pet();pet.setId(PET);when(petTagPermissionService.validateAndGetTaggablePet(USER,PET)).thenReturn(pet); service.createPost(r,USER); verify(postMediaRepository).saveAll(any());verify(petTimelineService).createSocialPostEvent(eq(pet),any()); }
    @Test void createPost_InvalidPartitions_RejectsNullBlankPrivacyContentAndPetBoundary() { active(); assertThatThrownBy(()->service.createPost(null,USER)).isInstanceOf(BadRequestException.class); var blank=create(" ");assertThatThrownBy(()->service.createPost(blank,USER)).isInstanceOf(BadRequestException.class); var noPrivacy=create("x");noPrivacy.setPrivacy(" ");assertThatThrownBy(()->service.createPost(noPrivacy,USER)).isInstanceOf(BadRequestException.class);var badPet=create("x");badPet.setPetId(0L);assertThatThrownBy(()->service.createPost(badPet,USER)).isInstanceOf(BadRequestException.class); }
    @Test void createPost_InvalidMediaPartitions_RejectsOverLimitNullUrlTypeAndNegativeValues() { active();var r=create("x");r.setMedia(java.util.Collections.nCopies(11,media()));assertThatThrownBy(()->service.createPost(r,USER)).isInstanceOf(BadRequestException.class);r.setMedia(java.util.Collections.singletonList(null));assertThatThrownBy(()->service.createPost(r,USER)).isInstanceOf(BadRequestException.class);var bad=media();bad.setMediaUrl(" ");r.setMedia(List.of(bad));assertThatThrownBy(()->service.createPost(r,USER)).isInstanceOf(BadRequestException.class);bad=media();bad.setMediaType("bad");r.setMedia(List.of(bad));assertThatThrownBy(()->service.createPost(r,USER)).isInstanceOf(BadRequestException.class);bad=media();bad.setFileSize(-1L);r.setMedia(List.of(bad));assertThatThrownBy(()->service.createPost(r,USER)).isInstanceOf(BadRequestException.class); }
    @Test void createPostWithFiles_ValidAndBoundaries() { active();service.createPostWithFiles(USER,null,"caption","friends",List.of());verify(fileStorageService).storePostMediaFiles(List.of());assertThatThrownBy(()->service.createPostWithFiles(USER,null," ","public",List.of())).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.createPostWithFiles(USER,null,"x","bad",List.of())).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.createPostWithFiles(USER,null,"x","public",java.util.Collections.nCopies(11,null))).isInstanceOf(BadRequestException.class); }
    @Test void createPostWithFiles_UploadedMediaAndTaggedPet_MapsUploadedFile() { active(); com.petcare.backend.model.Pet pet=new com.petcare.backend.model.Pet();pet.setId(PET);when(petTagPermissionService.validateAndGetTaggablePet(USER,PET)).thenReturn(pet); when(fileStorageService.storePostMediaFiles(any())).thenReturn(List.of(UploadFileResponse.builder().mediaType("video").mediaUrl("u").fileSize(2L).build())); service.createPostWithFiles(USER,PET,"caption","public",List.of(org.mockito.Mockito.mock(org.springframework.web.multipart.MultipartFile.class)));verify(postMediaRepository).saveAll(any());verify(petTimelineService).createSocialPostEvent(eq(pet),any()); }
    @Test void getPostById_ValidMissingAndIdBoundaries() { Post p=post();existing(p); assertThat(service.getPostById(POST,USER)).isNotNull();when(postRepository.findByIdAndStatusNot(POST,PostStatus.DELETED)).thenReturn(Optional.empty());assertThatThrownBy(()->service.getPostById(POST,USER)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.getPostById(0L,USER)).isInstanceOf(BadRequestException.class); }
    @Test void pageOperations_EmptyDataPaginationAndLimits() { var empty=new PageImpl<Post>(List.of(),org.springframework.data.domain.PageRequest.of(0,50),0);when(postRepository.findVisibleFeedPosts(eq(USER),any(),any(),any(),any())).thenReturn(empty);when(postRepository.findByUser_IdAndStatusNotOrderByCreatedAtDesc(eq(USER),any(),any())).thenReturn(empty);assertThat(service.getPublicPosts(USER,0,50).getContent()).isEmpty();assertThat(service.getMyPosts(USER,0,500).getSize()).isEqualTo(50);assertThatThrownBy(()->service.getMyPosts(USER,-1,1)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.getMyPosts(USER,0,0)).isInstanceOf(BadRequestException.class); }
    @Test void getUserPosts_SelfFriendStrangerAndMissingProfile() { var empty=new PageImpl<Post>(List.of());when(postRepository.findByUser_IdAndStatusNotOrderByCreatedAtDesc(eq(USER),any(),any())).thenReturn(empty);assertThat(service.getUserPosts(USER,USER,0,1).getContent()).isEmpty();when(userRepository.existsById(PET)).thenReturn(true);when(postRepository.findByUser_IdAndStatusAndPrivacyInOrderByCreatedAtDesc(eq(PET),any(),any(),any())).thenReturn(empty);when(friendService.areFriends(USER,PET)).thenReturn(true);service.getUserPosts(PET,USER,0,1);when(friendService.areFriends(USER,PET)).thenReturn(false);service.getUserPosts(PET,USER,0,1);when(userRepository.existsById(PET)).thenReturn(false);assertThatThrownBy(()->service.getUserPosts(PET,USER,0,1)).isInstanceOf(ResourceNotFoundException.class); }
    @Test void getPetPosts_ExistingMissingAndIdBoundary() { var empty=new PageImpl<Post>(List.of());when(petRepository.existsById(PET)).thenReturn(true);when(postRepository.findVisiblePetPosts(eq(PET),eq(USER),any(),any(),any(),any(),any())).thenReturn(empty);assertThat(service.getPetPosts(PET,USER,0,1).getContent()).isEmpty();when(petRepository.existsById(PET)).thenReturn(false);assertThatThrownBy(()->service.getPetPosts(PET,USER,0,1)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.getPetPosts(0L,USER,0,1)).isInstanceOf(BadRequestException.class); }
    @Test void updatePost_AllOptionalFieldsAndMediaReplacement_AreApplied() { Post p=post();existing(p);var r=new UpdatePostRequest();r.setCaption(" new ");r.setPrivacy("private");r.setCommentsLocked(true);r.setPetId(PET);r.setMedia(List.of(media()));service.updatePost(POST,r,USER);assertThat(p.getCaption()).isEqualTo("new");assertThat(p.getPrivacy()).isEqualTo(PostPrivacy.PRIVATE);assertThat(p.getCommentsLocked()).isTrue();verify(postMediaRepository).deleteByPost_Id(POST); }
    @Test void updatePost_InvalidRequestPrivacyContentAndPetBoundary_AreRejected() { Post p=post();existing(p);assertThatThrownBy(()->service.updatePost(POST,null,USER)).isInstanceOf(BadRequestException.class);var invalidPrivacy=new UpdatePostRequest();invalidPrivacy.setPrivacy("bad");assertThatThrownBy(()->service.updatePost(POST,invalidPrivacy,USER)).isInstanceOf(BadRequestException.class);var noContent=new UpdatePostRequest();noContent.setCaption(" ");noContent.setMedia(List.of());assertThatThrownBy(()->service.updatePost(POST,noContent,USER)).isInstanceOf(BadRequestException.class);var invalidPet=new UpdatePostRequest();invalidPet.setPetId(0L);assertThatThrownBy(()->service.updatePost(POST,invalidPet,USER)).isInstanceOf(BadRequestException.class); }
    @Test void updatePost_MediaUnchanged_UsesExistingMediaForContentValidation() { Post p=post();p.setCaption(" ");existing(p);when(postMediaRepository.findByPost_IdOrderByDisplayOrderAsc(POST)).thenReturn(List.of(org.mockito.Mockito.mock(com.petcare.backend.model.PostMedia.class)));service.updatePost(POST,new UpdatePostRequest(),USER);when(postMediaRepository.findByPost_IdOrderByDisplayOrderAsc(POST)).thenReturn(List.of());assertThatThrownBy(()->service.updatePost(POST,new UpdatePostRequest(),USER)).isInstanceOf(BadRequestException.class); }
    @Test void buildPostResponse_CommentsRepliesAndNullableBranches_AreMapped() { Post p=post();com.petcare.backend.model.PostComment root=com.petcare.backend.model.PostComment.builder().id(21L).post(p).status(CommentStatus.VISIBLE).build();com.petcare.backend.model.PostComment reply=com.petcare.backend.model.PostComment.builder().id(22L).post(p).status(CommentStatus.VISIBLE).depth(2).build();when(postCommentRepository.findByPost_IdAndParentCommentIdIsNullAndStatusOrderByCreatedAtDesc(POST,CommentStatus.VISIBLE)).thenReturn(List.of(root));when(postCommentRepository.findByParentCommentIdAndStatusOrderByCreatedAtAsc(21L,CommentStatus.VISIBLE)).thenReturn(List.of(reply));when(postMapper.toCommentResponse(any(),anyList(),any(),org.mockito.ArgumentMatchers.anyLong(),any(),any())).thenReturn(new PostCommentResponse());PostResponse response=service.buildPostResponse(p,null);assertThat(response.getComments()).hasSize(1);service.buildPostResponse(p,USER); }
    @Test void createPost_MediaNullableFieldsAndIdNullBoundaries_AreHandled() { active();var request=create("x");var item=media();item.setMediaType(null);item.setFileSize(null);item.setDisplayOrder(5);request.setMedia(List.of(item));service.createPost(request,USER);assertThatThrownBy(()->service.getPostById(null,USER)).isInstanceOf(BadRequestException.class);assertThatThrownBy(()->service.createPostWithFiles(USER,null,"x",null,null)).isInstanceOf(BadRequestException.class); }
    @Test void buildPostResponse_TaggedPetSavedAndTerminalComment_AreMapped() { Post p=post();p.setPetId(PET);p.setUser(null);com.petcare.backend.model.Pet pet=new com.petcare.backend.model.Pet();pet.setId(PET);pet.setName("Milo");when(petRepository.findAllById(List.of(PET))).thenReturn(List.of(pet));com.petcare.backend.model.PostComment terminal=com.petcare.backend.model.PostComment.builder().id(31L).post(p).status(CommentStatus.VISIBLE).depth(2).build();when(postCommentRepository.findByPost_IdAndParentCommentIdIsNullAndStatusOrderByCreatedAtDesc(POST,CommentStatus.VISIBLE)).thenReturn(List.of(terminal));when(postMapper.toCommentResponse(any(),anyList(),any(),org.mockito.ArgumentMatchers.anyLong(),any(),any())).thenReturn(new PostCommentResponse());assertThat(service.buildPostResponse(p,USER).getComments()).hasSize(1); }
    @Test void deletePost_AuthorizedPost_CleansDependentData() { Post p=post();existing(p);service.deletePost(POST,USER);verify(commentReactionRepository).deleteByComment_Post_Id(POST);verify(postCommentRepository).deleteByPost_Id(POST);verify(postReactionRepository).deleteByPost_Id(POST);verify(postMediaRepository).deleteByPost_Id(POST);verify(postRepository).delete(p); }
}
